version: '3.8'

services:
  nginx-proxy-manager:
    image: jc21/nginx-proxy-manager:latest
    ports:
      - '80:80'
      - '443:443'
      - '127.0.0.1:81:81'
    volumes:
      - ./npm/data:/data
      - ./npm/letsencrypt:/etc/letsencrypt
    networks:
      - homelab_network

  portainer:
    image: portainer/portainer-ce
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    networks:
      - homelab_network

  n8n:
    image: n8nio/n8n
    environment:
      - WEBHOOK_URL=https://n8n.home.lan
    volumes:
      - n8n_data:/home/node/.n8n
    networks:
      - homelab_network

  grafana:
    image: grafana/grafana
    volumes:
      - grafana_data:/var/lib/grafana
    networks:
      - homelab_network

networks:
  homelab_network:
    driver: bridge

volumes:
  n8n_data:
  grafana_data: